version: "3.1"

services:
  mysql:
    image: mysql
    restart: always
    container_name: node_api_database
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: node_api

  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev

volumes:
  mysql-data:
    driver: "local"